import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";
import "../components/UIkit/css/uikit.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={`uk-background-muted ${inter.className}`}>{children}</body>
    <Script src="/UIkit/js/uikit.js" />
    <Script src="/UIkit/js/uikit-icons.js" />
  </html>
);

export default RootLayout;
